# NOTE: This config is for golangci-lint v1.x (latest stable, not v2.x preview)
# If you are using golangci-lint v2.x, see https://github.com/golangci/golangci-lint/blob/master/.github/UPGRADE_V2.md
version: "2"

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: readonly
  concurrency: 4
  build-tags: []
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocyclo
    - revive
    - misspell
    - unparam
    - prealloc
    - gosec
    - bodyclose
    - noctx
    - errorlint
    - wrapcheck
    - nilnil
    - sqlclosecheck
    - dogsled
    - dupl
    - durationcheck
    - thelper
    - whitespace
    - asasalint
    - bidichk
    - contextcheck
    - musttag
    - nakedret

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
