name: Model/Schema Drift Detection

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  model-schema-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.22"

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "20"

      - name: Install OpenAPI Generator CLI (npm)
        run: |
          npm install --global @openapitools/openapi-generator-cli

      - name: Download latest Huntress OpenAPI/Swagger spec
        run: |
          mkdir -p build
          curl -sSfL https://api.huntress.io/swagger_doc.json -o build/swagger_doc.json

      - name: Generate Go models from OpenAPI/Swagger spec
        run: |
          mkdir -p build/openapi-models
          npx openapi-generator-cli generate -i build/swagger_doc.json -g go -o build/openapi-models --skip-validate-spec

      - name: Diff generated models with hand-written models
        run: |
          diff -ruN build/openapi-models/model pkg/huntress/ > build/model-schema-diff.txt || true
          if [ -s build/model-schema-diff.txt ]; then
            echo "Model/schema drift detected!"
            cat build/model-schema-diff.txt
          else
            echo "No model/schema drift detected."
          fi

      - name: Upload model/schema diff artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: model-schema-diff
          path: build/model-schema-diff.txt
