name: Model/Schema Drift Detection

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  model-schema-drift:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "1.22"

      - name: Install OpenAPI Generator CLI
        run: |
          if ! command -v openapi-generator-cli >/dev/null 2>&1; then
            wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.6.0/openapi-generator-cli-7.6.0.jar -O openapi-generator-cli.jar
            echo -e '#!/bin/sh\nexec java -jar "$PWD/openapi-generator-cli.jar" "$@"' > openapi-generator-cli
            chmod +x openapi-generator-cli
            sudo mv openapi-generator-cli /usr/local/bin/
            sudo mv openapi-generator-cli.jar /usr/local/bin/
          fi

      - name: Download latest Huntress OpenAPI/Swagger spec
        run: |
          mkdir -p build
          curl -sSfL https://api.huntress.io/swagger_doc.json -o build/swagger_doc.json

      - name: Generate Go models from OpenAPI/Swagger spec
        run: |
          mkdir -p build/openapi-models
          openapi-generator-cli generate -i build/swagger_doc.json -g go -o build/openapi-models --skip-validate-spec

      - name: Diff generated models with hand-written models
        id: diff
        run: |
          set -e
          diff -ruN build/openapi-models/model pkg/huntress/ > build/model-schema-diff.txt || true
          if [ -s build/model-schema-diff.txt ]; then
            echo "Model/schema drift detected!"
            exit 1
          else
            echo "No model/schema drift detected."
          fi

      - name: Upload model/schema diff artifact (if drift detected)
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: model-schema-diff
          path: build/model-schema-diff.txt
