# OSSF Scorecard workflow for security best practices
name: OSSF Scorecard
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 12 * * 1"

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: OSSF Scorecard action
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: ossf/scorecard-action@ea651e62978af7915d09fe2e282747c798bf2dab # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif

      - name: Upload Scorecard results to GitHub Security tab
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: github/codeql-action/upload-sarif@3d392940475e4c472e143ff2fd41aaffb1178094 # codeql-bundle-20221007
        with:
          sarif_file: results.sarif

      - name: Run OSSF attestation script
        run: ./ossf-attest.sh

      - name: Upload OSSF attestation artifacts
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: ossf-attestation
          path: |
            golangci-lint.txt
            gosec.txt
            govulncheck.txt
            git-secrets.txt
            sbom.json
            test-results.txt
            coverage.txt

      - name: Run golangci-lint (v2)
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: golangci/golangci-lint-action@25e2cdc5eb1d7a04fdc45ff538f1a00e960ae128 # v8.0.0
        with:
          version: v2.0.2
          args: --output.format=github-actions --timeout=5m
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: false
          skip-cache: false
          install-mode: binary
