# OSSF Scorecard workflow for security best practices
name: OSSF Scorecard
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  schedule:
    - cron: "0 12 * * 1"

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout code
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: OSSF Scorecard action
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186 # v2.4.1
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard results to GitHub Security tab
        # OSSF Scorecard: SHA pinning required for supply chain security
        uses: github/codeql-action/upload-sarif@3d392940475e4c472e143ff2fd41aaffb1178094 # codeql-bundle-20221007
        with:
          sarif_file: results.sarif

  ossf-artifacts:
    runs-on: ubuntu-latest
    needs: scorecard
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install security tools
        run: |
          sudo apt-get update
          sudo apt-get install -y git curl make
          # Install golangci-lint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin v2.1.6
          # Install gosec
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          # Install govulncheck
          go install golang.org/x/vuln/cmd/govulncheck@latest
          # Install git-secrets
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets && sudo make install && cd .. && rm -rf git-secrets
          # Add Go bin to PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run OSSF attestation script
        run: ./ossf-attest.sh

      - name: Upload OSSF attestation artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ossf-attestation
          path: |
            golangci-lint.txt
            gosec.txt
            govulncheck.txt
            git-secrets.txt
            sbom.json
            test-results.txt
            coverage.txt

      - name: Run golangci-lint (v2)
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6
          args: --timeout=5m
          github-token: ${{ secrets.GITHUB_TOKEN }}
          only-new-issues: false
          skip-cache: false
          install-mode: binary
